name = "kofusai-api"
main = "index.js" # あなたのファイル名が index.js の場合
compatibility_date = "2024-01-01"

# D1 (重複防止キャッシュ)
[[d1_databases]]
binding = "DB"
database_name = "kofusai-db"
database_id = "c87f679f-b074-4d48-876f-a841ce01f0d8" # npx wrangler d1 list で確認！

# Vectorize (全件検索)
[[vectorize]]
binding = "VECTOR_DB"
index_name = "kofusai-vector" # 再作成したsなしの名前
